In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Housing.csv")

In [3]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [4]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [5]:
df.tail()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [6]:
area = df["area"]

In [7]:
area

0      7420
1      8960
2      9960
3      7500
4      7420
       ...
540    3000
541    2400
542    3620
543    2910
544    3850
Name: area, Length: 545, dtype: int64

In [8]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [9]:
df1 = df.drop(columns="area",axis=1)

In [10]:
df1

,price,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [11]:
import numpy as np

In [12]:
array = np.array([1,2,3,4,5,6])

In [13]:
array

array([1, 2, 3, 4, 5, 6])

In [14]:
array = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

In [15]:
array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [16]:
array = np.zeros((3,3))

In [17]:
array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
array = np.zeros((2,3))

In [19]:
array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
array = np.array([1,2,3,4,5,6])

In [21]:
re_array = array.reshape((2,3))

In [22]:
re_array

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
array

array([1, 2, 3, 4, 5, 6])

In [24]:
np.mean(array)

3.5

In [25]:
np.sum(array)

21

In [26]:
for i in range(10):
    if i == 5:
        continue

In [27]:
print(i)

9

In [28]:
for i in range(10):
    if i == 7:
        continue
    print(i)

0
1
2
3
4
5
6
8
9