In [1]:
import pandas as pd
import numpy as np

#creating dataset

In [2]:
data ={
    "name":["sai","dev","vandana","pramodh"],
    "Age":[25,26,27,np.NaN],
    "department":["Hr","It","Sales","It"],
    "Salary":[1000,1100,1200,1300]
}

#data frame

In [3]:
df = pd.DataFrame(data)

In [4]:
df

      name   Age department  Salary
0      sai  25.0         Hr    1000
1      dev  26.0         It    1100
2  vandana  27.0      Sales    1200
3  pramodh   NaN         It    1300

#Filling null values with mean

In [5]:
df["Age"]=df["Age"].fillna(round(df["Age"].mean()))

In [6]:
df

      name   Age department  Salary
0      sai  25.0         Hr    1000
1      dev  26.0         It    1100
2  vandana  27.0      Sales    1200
3  pramodh  26.0         It    1300

#getting info

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        4 non-null      object
 1   Age         4 non-null      float64
 2   department  4 non-null      object
 3   Salary      4 non-null      int64
dtypes: float64(1), int64(1), object(2)
memory usage: 256.0+ bytes

#changing datatype

In [8]:
df["Age"] = df["Age"].astype("int64")

In [9]:
df.info

<bound method DataFrame.info of       name  Age department  Salary
0      sai   25         Hr    1000
1      dev   26         It    1100
2  vandana   27      Sales    1200
3  pramodh   26         It    1300>

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        4 non-null      object
 1   Age         4 non-null      int64
 2   department  4 non-null      object
 3   Salary      4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 256.0+ bytes

In [11]:
df

      name  Age department  Salary
0      sai   25         Hr    1000
1      dev   26         It    1100
2  vandana   27      Sales    1200
3  pramodh   26         It    1300

In [12]:
df.describe()

             Age       Salary
count   4.000000     4.000000
mean   26.000000  1150.000000
std     0.816497   129.099445
min    25.000000  1000.000000
25%    25.750000  1075.000000
50%    26.000000  1150.000000
75%    26.250000  1225.000000
max    27.000000  1300.000000

In [13]:
df1 = df[["name","Age"]]

In [14]:
df1

      name  Age
0      sai   25
1      dev   26
2  vandana   27
3  pramodh   26

#locate 1 to 3 rows

In [15]:
df.iloc[1:3]

      name  Age department  Salary
1      dev   26         It    1100
2  vandana   27      Sales    1200

In [16]:
df.loc[2,"Salary"]

1200

In [17]:
df.loc[0:3,["name","Age"]]

      name  Age
0      sai   25
1      dev   26
2  vandana   27
3  pramodh   26

In [18]:
df["Age"]>26

0    False
1    False
2     True
3    False
Name: Age, dtype: bool

In [19]:
df[(df["Age"]>26) & (df["Age"] == 27)]

      name  Age department  Salary
2  vandana   27      Sales    1200

#GROUP BY

In [20]:
df.groupby("department")["Salary"].mean()

department
Hr       1000.0
It       1200.0
Sales    1200.0
Name: Salary, dtype: float64

In [21]:
df

      name  Age department  Salary
0      sai   25         Hr    1000
1      dev   26         It    1100
2  vandana   27      Sales    1200
3  pramodh   26         It    1300

#MULTI AGG

In [22]:
df.groupby("department").agg({
    "Age":"mean",
    "Salary":"mean"
})

             Age  Salary
department
Hr          25.0  1000.0
It          26.0  1200.0
Sales       27.0  1200.0

#SORT_VALUES

In [23]:
df.sort_values(["Salary","Age"])

      name  Age department  Salary
0      sai   25         Hr    1000
1      dev   26         It    1100
2  vandana   27      Sales    1200
3  pramodh   26         It    1300

In [24]:
df.sort_values("Salary",ascending = False)

      name  Age department  Salary
3  pramodh   26         It    1300
2  vandana   27      Sales    1200
1      dev   26         It    1100
0      sai   25         Hr    1000

In [25]:
df["salary_k"] = df["Salary"]/1000

In [26]:
df

      name  Age department  Salary  salary_k
0      sai   25         Hr    1000       1.0
1      dev   26         It    1100       1.1
2  vandana   27      Sales    1200       1.2
3  pramodh   26         It    1300       1.3

#VALUE COUNT

In [27]:
df["Age"].value_counts()

Age
26    2
25    1
27    1
Name: count, dtype: int64